### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by camoo** [undjike/camoo-laravel-notification-channel#1]
Really nice implementation!
Not am issue but just some suggestions.

* SendMessageRequest::execute(CamooMessage $message, $addressee, array $auth = null): \Camoo\Sms\Response\Message

You can get the sms `id` just with `$response->getId()` or over property with `$response->id`

**Comment by undjike** [comment]
Wow, nice catch!!

Be sure that your suggestions have been taken into account.

Glad to see you like the implementation.
Feel free to suggest improvements and let's discuss them.
